// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Graphql_Codegen = require("./Graphql_Codegen.bs.js");
var ReasonReactApollo_Make = require("../src/ReasonReactApollo_Make.bs.js");

function parse(prim) {
  return prim;
}

var include = ReasonReactApollo_Make.MakeProject(/* module */[/* parse */parse]);

var verifyGraphQLType = Graphql_Codegen.verifyGraphQLType;

var getField = Graphql_Codegen.getField;

var getNullableField = Graphql_Codegen.getNullableField;

var getArray = Graphql_Codegen.getArray;

var getNullableArray = Graphql_Codegen.getNullableArray;

var makeDecoder = Graphql_Codegen.makeDecoder;

var makeNullableDecoder = Graphql_Codegen.makeNullableDecoder;

var decodeInt = Graphql_Codegen.decodeInt;

var getString = Graphql_Codegen.getString;

var getNullableString = Graphql_Codegen.getNullableString;

var getFloat = Graphql_Codegen.getFloat;

var getNullableFloat = Graphql_Codegen.getNullableFloat;

var getInt = Graphql_Codegen.getInt;

var getNullableInt = Graphql_Codegen.getNullableInt;

var getBool = Graphql_Codegen.getBool;

var getNullableBool = Graphql_Codegen.getNullableBool;

var decodeEnum = Graphql_Codegen.decodeEnum;

var getEnum = Graphql_Codegen.getEnum;

var getNullableEnum = Graphql_Codegen.getNullableEnum;

var cacheControlScope_enumToJs = Graphql_Codegen.cacheControlScope_enumToJs;

var cacheControlScope_enumFromJs = Graphql_Codegen.cacheControlScope_enumFromJs;

var cacheControlScopeMap = Graphql_Codegen.cacheControlScopeMap;

var Query = Graphql_Codegen.Query;

var Todo = Graphql_Codegen.Todo;

var User = Graphql_Codegen.User;

var Mutation = Graphql_Codegen.Mutation;

var CreateUserInput = Graphql_Codegen.CreateUserInput;

var MakeQuery = include[0];

exports.verifyGraphQLType = verifyGraphQLType;
exports.getField = getField;
exports.getNullableField = getNullableField;
exports.getArray = getArray;
exports.getNullableArray = getNullableArray;
exports.makeDecoder = makeDecoder;
exports.makeNullableDecoder = makeNullableDecoder;
exports.decodeInt = decodeInt;
exports.getString = getString;
exports.getNullableString = getNullableString;
exports.getFloat = getFloat;
exports.getNullableFloat = getNullableFloat;
exports.getInt = getInt;
exports.getNullableInt = getNullableInt;
exports.getBool = getBool;
exports.getNullableBool = getNullableBool;
exports.decodeEnum = decodeEnum;
exports.getEnum = getEnum;
exports.getNullableEnum = getNullableEnum;
exports.cacheControlScope_enumToJs = cacheControlScope_enumToJs;
exports.cacheControlScope_enumFromJs = cacheControlScope_enumFromJs;
exports.cacheControlScopeMap = cacheControlScopeMap;
exports.Query = Query;
exports.Todo = Todo;
exports.User = User;
exports.Mutation = Mutation;
exports.CreateUserInput = CreateUserInput;
exports.MakeQuery = MakeQuery;
/* include Not a pure module */
